// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortLinkGeneration.DB;

#nullable disable

namespace ShortLinkGeneration.Migrations
{
    [DbContext(typeof(ShortLinkContext))]
    [Migration("20230604072705_ShortLinkDB")]
    partial class ShortLinkDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShortLinkGeneration.DB.Click", b =>
                {
                    b.Property<int>("ClickID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ClickTime")
                        .HasColumnType("datetime");

                    b.Property<int>("LinkID")
                        .HasColumnType("int");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClickID");

                    b.HasIndex("LinkID");

                    b.ToTable("Clicks");
                });

            modelBuilder.Entity("ShortLinkGeneration.DB.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDelayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxClicks")
                        .HasColumnType("int");

                    b.Property<string>("OriginalLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LinkID");

                    b.HasIndex("UserID");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("ShortLinkGeneration.DB.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShortLinkGeneration.DB.Click", b =>
                {
                    b.HasOne("ShortLinkGeneration.DB.Link", "Link")
                        .WithMany("Clicks")
                        .HasForeignKey("LinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("ShortLinkGeneration.DB.Link", b =>
                {
                    b.HasOne("ShortLinkGeneration.DB.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShortLinkGeneration.DB.Link", b =>
                {
                    b.Navigation("Clicks");
                });

            modelBuilder.Entity("ShortLinkGeneration.DB.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
